### ISSUE TITLE
Collecting Chest x-ray  Dataset for Covid-19 

### ISSUE THREAD

**Issue by kazimsayed954** [kazimsayed954/COVID-19-Detector-V1.1#1]

**Comment by ashwanisng** [comment]
can I contribute to this issue?

**Comment by kazimsayed954** [comment]
> can I contribute to this issue?

yes

**Comment by kazimsayed954** [comment]
> can I contribute to this issue?

but in different branch test

**Comment by ashwanisng** [comment]
okay

**Comment by kazimsayed954** [comment]
> > can I contribute to this issue?
> 
> but in different branch test

once the dataset is been finalize so u can contribute in master branch

**Comment by ashwanisng** [comment]
> > > can I contribute to this issue?
> > 
> > 
> > but in different branch test
> 
> once the dataset is been finalize so u can contribute in master branch

okay

**Comment by janmejai2002** [comment]
I think we can close this issue.

**Comment by ashwanisng** [comment]
Yup, now the dataset is finalized so we can close this issue. @kazimsayed954

**Comment by kazimsayed954** [comment]
Sure
